name: On PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
